export const signup = async (req, res) => {
  try {
  } catch (error) {
    console.log(error);
    return res.status(500).json({
      status: "fail",
      message: "internal server error",
      error,
    });
  }
};
export const login = async (req, res) => {
  try {
  } catch (error) {
    console.log(error);
    return res.status(500).json({
      status: "fail",
      message: "internal server error",
      error,
    });
  }
};
export const getHistory = async (req, res) => {
  try {
  } catch (error) {
    console.log(error);
    return res.status(500).json({
      status: "fail",
      message: "internal server error",
      error,
    });
  }
};
